services:
  drawio:
    image: jgraph/drawio:latest
    container_name: drawio
    restart: always
    environment:
      - TZ=${TZ}
      - PUBLIC_DNS=drawio.${DOMAIN}
      - DRAWIO_SERVER_URL=https://drawio.${DOMAIN}/
      - DRAWIO_BASE_URL=https://drawio.${DOMAIN}
    volumes:
      - ${STACK_PATH}/drawio/data:/data
    networks:
      - network_core
    labels:
      - traefik.enable=true
      - traefik.http.routers.drawio.rule=Host(`drawio.${DOMAIN}`)
      - traefik.http.routers.drawio.entrypoints=websecure
      - traefik.http.routers.drawio.tls=true
      - traefik.http.routers.drawio.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.drawio.service=drawio
      - traefik.http.services.drawio.loadbalancer.server.port=${DRAWIO_SERVICE_PORT}